package(default_visibility = ['//visibility:public'])

xcode_version(
  name = 'version26_2_0_17C52',
  version = '26.2.0.17C52',
  aliases = ['17C52', '26.2.0.17C52', '26', '26.2.0', '26.2'],
  default_ios_sdk_version = '26.2',
  default_tvos_sdk_version = '26.2',
  default_macos_sdk_version = '26.2',
  default_visionos_sdk_version = '26.2',
  default_watchos_sdk_version = '26.2',
)

xcode_config(
  name = 'host_xcodes',
  versions = [':version26_2_0_17C52'],
  default = ':version26_2_0_17C52',
)

available_xcodes(
  name = 'host_available_xcodes',
  versions = [':version26_2_0_17C52'],
  default = ':version26_2_0_17C52',
)
